# <center> ANALYSIS OF FOOTBALL DATA  </center>

### <center> USING PYTHON </center>

#### Libraries used : 
    (i)   Numpy
    (ii)  Pandas
    (iii) Matplot

In [3]:
import numpy as np
import pandas as pd 
from matplotlib as plt

SyntaxError: invalid syntax (<ipython-input-3-a3d04d5aa974>, line 3)

In [ ]:
# Creating Arrays

In [13]:
n1 = np.array([1,2,3,4,5])
n1

array([1, 2, 3, 4, 5])

In [14]:
n2 = np.array([[10,20,30,40],[40,30,20,10]])
n2

array([[10, 20, 30, 40],
       [40, 30, 20, 10]])

In [17]:
n3=np.zeros((1,2))
n3

array([[0., 0.]])

In [18]:
n4=np.zeros((5,5))
n4

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])